services:
  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4444      # <--- ¡AQUÍ defines la contraseña!
      POSTGRES_DB: TresoraBBDD
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d

