SELECT f.id_factura, df.id_detalle, df.cantidad * p.precio_base * ((100-f.descuento) / 100)
FROM facturas f
JOIN detalle_factura df ON df.id_factura = f.id_factura
JOIN producto p ON p.id_producto = df.id_producto 
				AND f.fecha_emision >= p.fecha_desde 
				AND f.fecha_emision < p.fecha_hasta

-------------------------PASOS PARA CREAR UNA FACTURA--------------------------------
CREAR LA FACTURA
VEREMOS SI HAY RESERVA ASOCIADA SI/NO
	SI ES UN SI, FECHA FIN DE RESERVA
	SI ES UN NO, FECHA DEL DÍA
VER LOS ELEMENTOS FACTURABLES AL CLIENTE (PRODUCTOS)
	EN LA TABLA PRODUCTOS_CLIENTE HAY UNA SERIE DE ELEMENTOS A SELECCIONAR
	FALTARIA UN CAMPO DE FACTURADO O NO 
	COGEREMOS TODOS LOS CAMPOS QUE NO ESTEN FACTURADOS Y SERAN LOS QUE AÑADIREMOS A LA FACTURA
	EN LA TABLA DE DETALLE_FACTURA AÑADIMOS TODOS LOS ELEMENTOS QUE ESTÁN EN PRODUCTOS CLIENTE QUE NO ESTEN FACTURADOS HASTA AHORA
UNA VEZ GENERADOS LOS DETALLES, ACTUALIZAMOS LOS ELEMENTOS DE PRODUCTO CLIENTE CON EL INDICADOR 'FACTURADO' A LOS ELEMENTOS QUE NO LO TENGAN

CREAR UN ID DE RESERVA ESTANDAR (0 o 99999999) Y QUE SEA EL PRODUCTO ESTANDAR (COMO UNA Posting Master)

ASUMIMOS QUE LAS RESERVAS CON HABITACION PAGAN SIEMPRE AL FINAL.

ASUMIMOS QUE UN PRODUCTO PUEDE SER CONSUMIDO SOLO SI TIENE USUARIO.