--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-06-17 19:18:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
--
-- TOC entry 5049 (class 1262 OID 32880)
-- Name: TresoraBBDD; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "TresoraBBDD" WITH TEMPLATE = template0 ENCODING = 'UTF8';


ALTER DATABASE "TresoraBBDD" OWNER TO postgres;

\connect "TresoraBBDD"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 42029)
-- Name: categorias_productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias_productos (
    id integer NOT NULL,
    nombre character varying(30) NOT NULL,
    descripcion character varying(80)
);


ALTER TABLE public.categorias_productos OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 42028)
-- Name: categorias_productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias_productos ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.categorias_productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 42171)
-- Name: contactos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contactos (
    id integer NOT NULL,
    id_usuario integer,
    nombre character varying(100) NOT NULL,
    correo character varying(70) NOT NULL,
    telefono character varying(20),
    departamento character varying(20) NOT NULL,
    mensaje text NOT NULL,
    fecha_envio timestamp without time zone,
    foto1 character varying(25),
    foto2 character varying(25)
);


ALTER TABLE public.contactos OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 42170)
-- Name: contactos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.contactos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.contactos_id_seq OWNER TO postgres;

--
-- TOC entry 5050 (class 0 OID 0)
-- Dependencies: 242
-- Name: contactos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.contactos_id_seq OWNED BY public.contactos.id;


--
-- TOC entry 238 (class 1259 OID 42124)
-- Name: detalles_facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_facturas (
    id integer NOT NULL,
    id_factura integer NOT NULL,
    id_producto_usuario integer NOT NULL
);


ALTER TABLE public.detalles_facturas OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 42123)
-- Name: detalles_facturas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalles_facturas ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.detalles_facturas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 42140)
-- Name: detalles_reserva; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalles_reserva (
    id integer NOT NULL,
    id_reserva integer,
    id_habitacion integer
);


ALTER TABLE public.detalles_reserva OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 42139)
-- Name: detalles_reserva_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalles_reserva ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.detalles_reserva_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 42205)
-- Name: entidad_hija; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entidad_hija (
    entidad_padre_id bigint,
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.entidad_hija OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 42204)
-- Name: entidad_hija_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entidad_hija ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entidad_hija_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 42211)
-- Name: entidad_padre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entidad_padre (
    id bigint NOT NULL,
    nombre character varying(255)
);


ALTER TABLE public.entidad_padre OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 42210)
-- Name: entidad_padre_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entidad_padre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entidad_padre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 42100)
-- Name: facturas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.facturas (
    id integer NOT NULL,
    id_usuario integer NOT NULL,
    id_metodo_pago integer NOT NULL,
    id_detalle integer NOT NULL,
    id_hotel integer NOT NULL,
    fecha_emision date NOT NULL,
    estado character varying NOT NULL,
    observaciones character varying(80)
);


ALTER TABLE public.facturas OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 42099)
-- Name: facturas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.facturas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.facturas_id_seq OWNER TO postgres;

--
-- TOC entry 5051 (class 0 OID 0)
-- Dependencies: 235
-- Name: facturas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.facturas_id_seq OWNED BY public.facturas.id;


--
-- TOC entry 230 (class 1259 OID 42046)
-- Name: habitaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.habitaciones (
    id integer NOT NULL,
    id_hotel integer NOT NULL,
    id_producto integer NOT NULL,
    numero_habitacion integer NOT NULL,
    piso integer NOT NULL,
    tipo character varying(25) NOT NULL,
    capacidad integer NOT NULL,
    estado_ocupacion character varying(30) NOT NULL
);


ALTER TABLE public.habitaciones OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 42045)
-- Name: habitaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.habitaciones ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.habitaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 41996)
-- Name: hoteles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hoteles (
    id integer NOT NULL,
    nombre character varying(30) NOT NULL,
    ciudad character varying(50) NOT NULL,
    direccion character varying(70) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(30) NOT NULL
);


ALTER TABLE public.hoteles OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 41995)
-- Name: hoteles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hoteles ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.hoteles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 42185)
-- Name: limpieza_habitaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.limpieza_habitaciones (
    id integer NOT NULL,
    id_usuario integer NOT NULL,
    id_habitacion integer NOT NULL,
    fecha_limpieza date NOT NULL,
    hora_limpieza time without time zone NOT NULL,
    foto1 character varying(255),
    foto2 character varying(255)
);


ALTER TABLE public.limpieza_habitaciones OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 42184)
-- Name: limpieza_habitaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.limpieza_habitaciones_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.limpieza_habitaciones_id_seq OWNER TO postgres;

--
-- TOC entry 5052 (class 0 OID 0)
-- Dependencies: 244
-- Name: limpieza_habitaciones_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.limpieza_habitaciones_id_seq OWNED BY public.limpieza_habitaciones.id;


--
-- TOC entry 224 (class 1259 OID 42021)
-- Name: metodo_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.metodo_pago (
    id integer NOT NULL,
    nombre character varying(30) NOT NULL,
    descripcion character varying
);


ALTER TABLE public.metodo_pago OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 42020)
-- Name: metodo_pago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.metodo_pago ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.metodo_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 42035)
-- Name: productos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos (
    id integer NOT NULL,
    id_categoria integer NOT NULL,
    id_hotel integer NOT NULL,
    nombre character varying(30) NOT NULL,
    descripcion character varying(80) NOT NULL,
    precio_base numeric(15,2) NOT NULL,
    activo boolean,
    fecha_desde date,
    fecha_hasta date
);


ALTER TABLE public.productos OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 42155)
-- Name: productos_habitaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos_habitaciones (
    id_producto integer NOT NULL,
    id_habitacion integer NOT NULL
);


ALTER TABLE public.productos_habitaciones OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 42034)
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 42079)
-- Name: productos_usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.productos_usuarios (
    id integer NOT NULL,
    id_producto integer NOT NULL,
    id_usuario integer NOT NULL,
    fecha date,
    cantidad integer,
    descuento integer,
    id_reserva integer,
    facturado boolean
);


ALTER TABLE public.productos_usuarios OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 42078)
-- Name: productos_usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.productos_usuarios ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.productos_usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 42062)
-- Name: reservas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservas (
    id integer NOT NULL,
    id_usuario integer NOT NULL,
    id_habitacion integer NOT NULL,
    fecha_entrada date NOT NULL,
    fecha_salida date NOT NULL,
    estado character varying(30) NOT NULL,
    pax integer NOT NULL,
    fecha_reserva timestamp without time zone NOT NULL,
    comentarios character varying(80)
);


ALTER TABLE public.reservas OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 42061)
-- Name: reservas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.reservas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reservas_id_seq OWNER TO postgres;

--
-- TOC entry 5053 (class 0 OID 0)
-- Dependencies: 231
-- Name: reservas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.reservas_id_seq OWNED BY public.reservas.id;


--
-- TOC entry 218 (class 1259 OID 41990)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    nombre_rol character varying(20) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 41989)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 42002)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    id_rol integer NOT NULL,
    id_hotel integer,
    nombre character varying(40) NOT NULL,
    apellidos character varying(70) NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    direccion character varying,
    telefono character varying(15) NOT NULL,
    fecha_nacimiento date NOT NULL,
    fecha_alta date NOT NULL,
    activo boolean,
    dni character varying(15)
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 42001)
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuarios_id_seq OWNER TO postgres;

--
-- TOC entry 5054 (class 0 OID 0)
-- Dependencies: 221
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- TOC entry 4807 (class 2604 OID 42174)
-- Name: contactos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contactos ALTER COLUMN id SET DEFAULT nextval('public.contactos_id_seq'::regclass);


--
-- TOC entry 4806 (class 2604 OID 42103)
-- Name: facturas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas ALTER COLUMN id SET DEFAULT nextval('public.facturas_id_seq'::regclass);


--
-- TOC entry 4808 (class 2604 OID 42188)
-- Name: limpieza_habitaciones id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.limpieza_habitaciones ALTER COLUMN id SET DEFAULT nextval('public.limpieza_habitaciones_id_seq'::regclass);


--
-- TOC entry 4805 (class 2604 OID 42065)
-- Name: reservas id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas ALTER COLUMN id SET DEFAULT nextval('public.reservas_id_seq'::regclass);


--
-- TOC entry 4804 (class 2604 OID 42005)
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- TOC entry 5020 (class 0 OID 42029)
-- Dependencies: 226
-- Data for Name: categorias_productos; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5037 (class 0 OID 42171)
-- Dependencies: 243
-- Data for Name: contactos; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5032 (class 0 OID 42124)
-- Dependencies: 238
-- Data for Name: detalles_facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5034 (class 0 OID 42140)
-- Dependencies: 240
-- Data for Name: detalles_reserva; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5041 (class 0 OID 42205)
-- Dependencies: 247
-- Data for Name: entidad_hija; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.entidad_hija VALUES (1, 1, 'Hija de Entidad-1');
INSERT INTO public.entidad_hija VALUES (2, 2, 'Hija de Entidad-2');
INSERT INTO public.entidad_hija VALUES (3, 3, 'Hija de Entidad-3');
INSERT INTO public.entidad_hija VALUES (4, 4, 'Hija de Entidad-4');
INSERT INTO public.entidad_hija VALUES (5, 5, 'Hija de Entidad-5');
INSERT INTO public.entidad_hija VALUES (6, 6, 'Hija de Entidad-6');
INSERT INTO public.entidad_hija VALUES (7, 7, 'Hija de Entidad-7');
INSERT INTO public.entidad_hija VALUES (8, 8, 'Hija de Entidad-8');
INSERT INTO public.entidad_hija VALUES (9, 9, 'Hija de Entidad-9');
INSERT INTO public.entidad_hija VALUES (10, 10, 'Hija de Entidad-10');
INSERT INTO public.entidad_hija VALUES (11, 11, 'Hija de Entidad-11');
INSERT INTO public.entidad_hija VALUES (12, 12, 'Hija de Entidad-12');
INSERT INTO public.entidad_hija VALUES (13, 13, 'Hija de Entidad-13');
INSERT INTO public.entidad_hija VALUES (14, 14, 'Hija de Entidad-14');
INSERT INTO public.entidad_hija VALUES (15, 15, 'Hija de Entidad-15');
INSERT INTO public.entidad_hija VALUES (16, 16, 'Hija de Entidad-16');
INSERT INTO public.entidad_hija VALUES (17, 17, 'Hija de Entidad-17');
INSERT INTO public.entidad_hija VALUES (18, 18, 'Hija de Entidad-18');
INSERT INTO public.entidad_hija VALUES (19, 19, 'Hija de Entidad-19');
INSERT INTO public.entidad_hija VALUES (20, 20, 'Hija de Entidad-20');
INSERT INTO public.entidad_hija VALUES (21, 21, 'Hija de Entidad-21');
INSERT INTO public.entidad_hija VALUES (22, 22, 'Hija de Entidad-22');
INSERT INTO public.entidad_hija VALUES (23, 23, 'Hija de Entidad-23');
INSERT INTO public.entidad_hija VALUES (24, 24, 'Hija de Entidad-24');
INSERT INTO public.entidad_hija VALUES (25, 25, 'Hija de Entidad-25');
INSERT INTO public.entidad_hija VALUES (26, 26, 'Hija de Entidad-26');
INSERT INTO public.entidad_hija VALUES (27, 27, 'Hija de Entidad-27');
INSERT INTO public.entidad_hija VALUES (28, 28, 'Hija de Entidad-28');
INSERT INTO public.entidad_hija VALUES (29, 29, 'Hija de Entidad-29');
INSERT INTO public.entidad_hija VALUES (30, 30, 'Hija de Entidad-30');
INSERT INTO public.entidad_hija VALUES (31, 31, 'Hija de Entidad-31');
INSERT INTO public.entidad_hija VALUES (32, 32, 'Hija de Entidad-32');
INSERT INTO public.entidad_hija VALUES (33, 33, 'Hija de Entidad-33');
INSERT INTO public.entidad_hija VALUES (34, 34, 'Hija de Entidad-34');
INSERT INTO public.entidad_hija VALUES (35, 35, 'Hija de Entidad-35');
INSERT INTO public.entidad_hija VALUES (36, 36, 'Hija de Entidad-36');
INSERT INTO public.entidad_hija VALUES (37, 37, 'Hija de Entidad-37');
INSERT INTO public.entidad_hija VALUES (38, 38, 'Hija de Entidad-38');
INSERT INTO public.entidad_hija VALUES (39, 39, 'Hija de Entidad-39');
INSERT INTO public.entidad_hija VALUES (40, 40, 'Hija de Entidad-40');
INSERT INTO public.entidad_hija VALUES (41, 41, 'Hija de Entidad-41');
INSERT INTO public.entidad_hija VALUES (42, 42, 'Hija de Entidad-42');
INSERT INTO public.entidad_hija VALUES (43, 43, 'Hija de Entidad-43');
INSERT INTO public.entidad_hija VALUES (44, 44, 'Hija de Entidad-44');
INSERT INTO public.entidad_hija VALUES (45, 45, 'Hija de Entidad-45');
INSERT INTO public.entidad_hija VALUES (46, 46, 'Hija de Entidad-46');
INSERT INTO public.entidad_hija VALUES (47, 47, 'Hija de Entidad-47');
INSERT INTO public.entidad_hija VALUES (48, 48, 'Hija de Entidad-48');
INSERT INTO public.entidad_hija VALUES (49, 49, 'Hija de Entidad-49');
INSERT INTO public.entidad_hija VALUES (50, 50, 'Hija de Entidad-50');
INSERT INTO public.entidad_hija VALUES (51, 51, 'Hija de Entidad-51');
INSERT INTO public.entidad_hija VALUES (52, 52, 'Hija de Entidad-52');
INSERT INTO public.entidad_hija VALUES (53, 53, 'Hija de Entidad-53');
INSERT INTO public.entidad_hija VALUES (54, 54, 'Hija de Entidad-54');
INSERT INTO public.entidad_hija VALUES (55, 55, 'Hija de Entidad-55');
INSERT INTO public.entidad_hija VALUES (56, 56, 'Hija de Entidad-56');
INSERT INTO public.entidad_hija VALUES (57, 57, 'Hija de Entidad-57');
INSERT INTO public.entidad_hija VALUES (58, 58, 'Hija de Entidad-58');
INSERT INTO public.entidad_hija VALUES (59, 59, 'Hija de Entidad-59');
INSERT INTO public.entidad_hija VALUES (60, 60, 'Hija de Entidad-60');
INSERT INTO public.entidad_hija VALUES (61, 61, 'Hija de Entidad-61');
INSERT INTO public.entidad_hija VALUES (62, 62, 'Hija de Entidad-62');
INSERT INTO public.entidad_hija VALUES (63, 63, 'Hija de Entidad-63');
INSERT INTO public.entidad_hija VALUES (64, 64, 'Hija de Entidad-64');
INSERT INTO public.entidad_hija VALUES (65, 65, 'Hija de Entidad-65');
INSERT INTO public.entidad_hija VALUES (66, 66, 'Hija de Entidad-66');
INSERT INTO public.entidad_hija VALUES (67, 67, 'Hija de Entidad-67');
INSERT INTO public.entidad_hija VALUES (68, 68, 'Hija de Entidad-68');
INSERT INTO public.entidad_hija VALUES (69, 69, 'Hija de Entidad-69');
INSERT INTO public.entidad_hija VALUES (70, 70, 'Hija de Entidad-70');
INSERT INTO public.entidad_hija VALUES (71, 71, 'Hija de Entidad-71');
INSERT INTO public.entidad_hija VALUES (72, 72, 'Hija de Entidad-72');
INSERT INTO public.entidad_hija VALUES (73, 73, 'Hija de Entidad-73');
INSERT INTO public.entidad_hija VALUES (74, 74, 'Hija de Entidad-74');
INSERT INTO public.entidad_hija VALUES (75, 75, 'Hija de Entidad-75');
INSERT INTO public.entidad_hija VALUES (76, 76, 'Hija de Entidad-76');
INSERT INTO public.entidad_hija VALUES (77, 77, 'Hija de Entidad-77');
INSERT INTO public.entidad_hija VALUES (78, 78, 'Hija de Entidad-78');
INSERT INTO public.entidad_hija VALUES (79, 79, 'Hija de Entidad-79');
INSERT INTO public.entidad_hija VALUES (80, 80, 'Hija de Entidad-80');
INSERT INTO public.entidad_hija VALUES (81, 81, 'Hija de Entidad-81');
INSERT INTO public.entidad_hija VALUES (82, 82, 'Hija de Entidad-82');
INSERT INTO public.entidad_hija VALUES (83, 83, 'Hija de Entidad-83');
INSERT INTO public.entidad_hija VALUES (84, 84, 'Hija de Entidad-84');
INSERT INTO public.entidad_hija VALUES (85, 85, 'Hija de Entidad-85');
INSERT INTO public.entidad_hija VALUES (86, 86, 'Hija de Entidad-86');
INSERT INTO public.entidad_hija VALUES (87, 87, 'Hija de Entidad-87');
INSERT INTO public.entidad_hija VALUES (88, 88, 'Hija de Entidad-88');
INSERT INTO public.entidad_hija VALUES (89, 89, 'Hija de Entidad-89');
INSERT INTO public.entidad_hija VALUES (90, 90, 'Hija de Entidad-90');
INSERT INTO public.entidad_hija VALUES (91, 91, 'Hija de Entidad-91');
INSERT INTO public.entidad_hija VALUES (92, 92, 'Hija de Entidad-92');
INSERT INTO public.entidad_hija VALUES (93, 93, 'Hija de Entidad-93');
INSERT INTO public.entidad_hija VALUES (94, 94, 'Hija de Entidad-94');
INSERT INTO public.entidad_hija VALUES (95, 95, 'Hija de Entidad-95');
INSERT INTO public.entidad_hija VALUES (96, 96, 'Hija de Entidad-96');
INSERT INTO public.entidad_hija VALUES (97, 97, 'Hija de Entidad-97');
INSERT INTO public.entidad_hija VALUES (98, 98, 'Hija de Entidad-98');
INSERT INTO public.entidad_hija VALUES (99, 99, 'Hija de Entidad-99');
INSERT INTO public.entidad_hija VALUES (100, 100, 'Hija de Entidad-100');


--
-- TOC entry 5043 (class 0 OID 42211)
-- Dependencies: 249
-- Data for Name: entidad_padre; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.entidad_padre VALUES (1, 'Entidad-1');
INSERT INTO public.entidad_padre VALUES (2, 'Entidad-2');
INSERT INTO public.entidad_padre VALUES (3, 'Entidad-3');
INSERT INTO public.entidad_padre VALUES (4, 'Entidad-4');
INSERT INTO public.entidad_padre VALUES (5, 'Entidad-5');
INSERT INTO public.entidad_padre VALUES (6, 'Entidad-6');
INSERT INTO public.entidad_padre VALUES (7, 'Entidad-7');
INSERT INTO public.entidad_padre VALUES (8, 'Entidad-8');
INSERT INTO public.entidad_padre VALUES (9, 'Entidad-9');
INSERT INTO public.entidad_padre VALUES (10, 'Entidad-10');
INSERT INTO public.entidad_padre VALUES (11, 'Entidad-11');
INSERT INTO public.entidad_padre VALUES (12, 'Entidad-12');
INSERT INTO public.entidad_padre VALUES (13, 'Entidad-13');
INSERT INTO public.entidad_padre VALUES (14, 'Entidad-14');
INSERT INTO public.entidad_padre VALUES (15, 'Entidad-15');
INSERT INTO public.entidad_padre VALUES (16, 'Entidad-16');
INSERT INTO public.entidad_padre VALUES (17, 'Entidad-17');
INSERT INTO public.entidad_padre VALUES (18, 'Entidad-18');
INSERT INTO public.entidad_padre VALUES (19, 'Entidad-19');
INSERT INTO public.entidad_padre VALUES (20, 'Entidad-20');
INSERT INTO public.entidad_padre VALUES (21, 'Entidad-21');
INSERT INTO public.entidad_padre VALUES (22, 'Entidad-22');
INSERT INTO public.entidad_padre VALUES (23, 'Entidad-23');
INSERT INTO public.entidad_padre VALUES (24, 'Entidad-24');
INSERT INTO public.entidad_padre VALUES (25, 'Entidad-25');
INSERT INTO public.entidad_padre VALUES (26, 'Entidad-26');
INSERT INTO public.entidad_padre VALUES (27, 'Entidad-27');
INSERT INTO public.entidad_padre VALUES (28, 'Entidad-28');
INSERT INTO public.entidad_padre VALUES (29, 'Entidad-29');
INSERT INTO public.entidad_padre VALUES (30, 'Entidad-30');
INSERT INTO public.entidad_padre VALUES (31, 'Entidad-31');
INSERT INTO public.entidad_padre VALUES (32, 'Entidad-32');
INSERT INTO public.entidad_padre VALUES (33, 'Entidad-33');
INSERT INTO public.entidad_padre VALUES (34, 'Entidad-34');
INSERT INTO public.entidad_padre VALUES (35, 'Entidad-35');
INSERT INTO public.entidad_padre VALUES (36, 'Entidad-36');
INSERT INTO public.entidad_padre VALUES (37, 'Entidad-37');
INSERT INTO public.entidad_padre VALUES (38, 'Entidad-38');
INSERT INTO public.entidad_padre VALUES (39, 'Entidad-39');
INSERT INTO public.entidad_padre VALUES (40, 'Entidad-40');
INSERT INTO public.entidad_padre VALUES (41, 'Entidad-41');
INSERT INTO public.entidad_padre VALUES (42, 'Entidad-42');
INSERT INTO public.entidad_padre VALUES (43, 'Entidad-43');
INSERT INTO public.entidad_padre VALUES (44, 'Entidad-44');
INSERT INTO public.entidad_padre VALUES (45, 'Entidad-45');
INSERT INTO public.entidad_padre VALUES (46, 'Entidad-46');
INSERT INTO public.entidad_padre VALUES (47, 'Entidad-47');
INSERT INTO public.entidad_padre VALUES (48, 'Entidad-48');
INSERT INTO public.entidad_padre VALUES (49, 'Entidad-49');
INSERT INTO public.entidad_padre VALUES (50, 'Entidad-50');
INSERT INTO public.entidad_padre VALUES (51, 'Entidad-51');
INSERT INTO public.entidad_padre VALUES (52, 'Entidad-52');
INSERT INTO public.entidad_padre VALUES (53, 'Entidad-53');
INSERT INTO public.entidad_padre VALUES (54, 'Entidad-54');
INSERT INTO public.entidad_padre VALUES (55, 'Entidad-55');
INSERT INTO public.entidad_padre VALUES (56, 'Entidad-56');
INSERT INTO public.entidad_padre VALUES (57, 'Entidad-57');
INSERT INTO public.entidad_padre VALUES (58, 'Entidad-58');
INSERT INTO public.entidad_padre VALUES (59, 'Entidad-59');
INSERT INTO public.entidad_padre VALUES (60, 'Entidad-60');
INSERT INTO public.entidad_padre VALUES (61, 'Entidad-61');
INSERT INTO public.entidad_padre VALUES (62, 'Entidad-62');
INSERT INTO public.entidad_padre VALUES (63, 'Entidad-63');
INSERT INTO public.entidad_padre VALUES (64, 'Entidad-64');
INSERT INTO public.entidad_padre VALUES (65, 'Entidad-65');
INSERT INTO public.entidad_padre VALUES (66, 'Entidad-66');
INSERT INTO public.entidad_padre VALUES (67, 'Entidad-67');
INSERT INTO public.entidad_padre VALUES (68, 'Entidad-68');
INSERT INTO public.entidad_padre VALUES (69, 'Entidad-69');
INSERT INTO public.entidad_padre VALUES (70, 'Entidad-70');
INSERT INTO public.entidad_padre VALUES (71, 'Entidad-71');
INSERT INTO public.entidad_padre VALUES (72, 'Entidad-72');
INSERT INTO public.entidad_padre VALUES (73, 'Entidad-73');
INSERT INTO public.entidad_padre VALUES (74, 'Entidad-74');
INSERT INTO public.entidad_padre VALUES (75, 'Entidad-75');
INSERT INTO public.entidad_padre VALUES (76, 'Entidad-76');
INSERT INTO public.entidad_padre VALUES (77, 'Entidad-77');
INSERT INTO public.entidad_padre VALUES (78, 'Entidad-78');
INSERT INTO public.entidad_padre VALUES (79, 'Entidad-79');
INSERT INTO public.entidad_padre VALUES (80, 'Entidad-80');
INSERT INTO public.entidad_padre VALUES (81, 'Entidad-81');
INSERT INTO public.entidad_padre VALUES (82, 'Entidad-82');
INSERT INTO public.entidad_padre VALUES (83, 'Entidad-83');
INSERT INTO public.entidad_padre VALUES (84, 'Entidad-84');
INSERT INTO public.entidad_padre VALUES (85, 'Entidad-85');
INSERT INTO public.entidad_padre VALUES (86, 'Entidad-86');
INSERT INTO public.entidad_padre VALUES (87, 'Entidad-87');
INSERT INTO public.entidad_padre VALUES (88, 'Entidad-88');
INSERT INTO public.entidad_padre VALUES (89, 'Entidad-89');
INSERT INTO public.entidad_padre VALUES (90, 'Entidad-90');
INSERT INTO public.entidad_padre VALUES (91, 'Entidad-91');
INSERT INTO public.entidad_padre VALUES (92, 'Entidad-92');
INSERT INTO public.entidad_padre VALUES (93, 'Entidad-93');
INSERT INTO public.entidad_padre VALUES (94, 'Entidad-94');
INSERT INTO public.entidad_padre VALUES (95, 'Entidad-95');
INSERT INTO public.entidad_padre VALUES (96, 'Entidad-96');
INSERT INTO public.entidad_padre VALUES (97, 'Entidad-97');
INSERT INTO public.entidad_padre VALUES (98, 'Entidad-98');
INSERT INTO public.entidad_padre VALUES (99, 'Entidad-99');
INSERT INTO public.entidad_padre VALUES (100, 'Entidad-100');


--
-- TOC entry 5030 (class 0 OID 42100)
-- Dependencies: 236
-- Data for Name: facturas; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5024 (class 0 OID 42046)
-- Dependencies: 230
-- Data for Name: habitaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5014 (class 0 OID 41996)
-- Dependencies: 220
-- Data for Name: hoteles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5039 (class 0 OID 42185)
-- Dependencies: 245
-- Data for Name: limpieza_habitaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5018 (class 0 OID 42021)
-- Dependencies: 224
-- Data for Name: metodo_pago; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5022 (class 0 OID 42035)
-- Dependencies: 228
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5035 (class 0 OID 42155)
-- Dependencies: 241
-- Data for Name: productos_habitaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5028 (class 0 OID 42079)
-- Dependencies: 234
-- Data for Name: productos_usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5026 (class 0 OID 42062)
-- Dependencies: 232
-- Data for Name: reservas; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5012 (class 0 OID 41990)
-- Dependencies: 218
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5016 (class 0 OID 42002)
-- Dependencies: 222
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5055 (class 0 OID 0)
-- Dependencies: 225
-- Name: categorias_productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categorias_productos_id_seq', 1, false);


--
-- TOC entry 5056 (class 0 OID 0)
-- Dependencies: 242
-- Name: contactos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contactos_id_seq', 1, false);


--
-- TOC entry 5057 (class 0 OID 0)
-- Dependencies: 237
-- Name: detalles_facturas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_facturas_id_seq', 1, false);


--
-- TOC entry 5058 (class 0 OID 0)
-- Dependencies: 239
-- Name: detalles_reserva_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalles_reserva_id_seq', 1, false);


--
-- TOC entry 5059 (class 0 OID 0)
-- Dependencies: 246
-- Name: entidad_hija_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entidad_hija_id_seq', 100, true);


--
-- TOC entry 5060 (class 0 OID 0)
-- Dependencies: 248
-- Name: entidad_padre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entidad_padre_id_seq', 100, true);


--
-- TOC entry 5061 (class 0 OID 0)
-- Dependencies: 235
-- Name: facturas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.facturas_id_seq', 1, false);


--
-- TOC entry 5062 (class 0 OID 0)
-- Dependencies: 229
-- Name: habitaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.habitaciones_id_seq', 1, false);


--
-- TOC entry 5063 (class 0 OID 0)
-- Dependencies: 219
-- Name: hoteles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hoteles_id_seq', 1, false);


--
-- TOC entry 5064 (class 0 OID 0)
-- Dependencies: 244
-- Name: limpieza_habitaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.limpieza_habitaciones_id_seq', 1, false);


--
-- TOC entry 5065 (class 0 OID 0)
-- Dependencies: 223
-- Name: metodo_pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.metodo_pago_id_seq', 1, false);


--
-- TOC entry 5066 (class 0 OID 0)
-- Dependencies: 227
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_id_seq', 1, false);


--
-- TOC entry 5067 (class 0 OID 0)
-- Dependencies: 233
-- Name: productos_usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.productos_usuarios_id_seq', 1, false);


--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 231
-- Name: reservas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reservas_id_seq', 1, false);


--
-- TOC entry 5069 (class 0 OID 0)
-- Dependencies: 217
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, false);


--
-- TOC entry 5070 (class 0 OID 0)
-- Dependencies: 221
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 1, false);


--
-- TOC entry 4818 (class 2606 OID 42033)
-- Name: categorias_productos categorias_productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias_productos
    ADD CONSTRAINT categorias_productos_pkey PRIMARY KEY (id);


--
-- TOC entry 4836 (class 2606 OID 42178)
-- Name: contactos contactos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contactos
    ADD CONSTRAINT contactos_pkey PRIMARY KEY (id);


--
-- TOC entry 4830 (class 2606 OID 42128)
-- Name: detalles_facturas detalles_facturas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_facturas
    ADD CONSTRAINT detalles_facturas_pkey PRIMARY KEY (id);


--
-- TOC entry 4832 (class 2606 OID 42144)
-- Name: detalles_reserva detalles_reserva_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_reserva
    ADD CONSTRAINT detalles_reserva_pkey PRIMARY KEY (id);


--
-- TOC entry 4840 (class 2606 OID 42209)
-- Name: entidad_hija entidad_hija_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entidad_hija
    ADD CONSTRAINT entidad_hija_pkey PRIMARY KEY (id);


--
-- TOC entry 4842 (class 2606 OID 42215)
-- Name: entidad_padre entidad_padre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entidad_padre
    ADD CONSTRAINT entidad_padre_pkey PRIMARY KEY (id);


--
-- TOC entry 4828 (class 2606 OID 42107)
-- Name: facturas facturas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_pkey PRIMARY KEY (id);


--
-- TOC entry 4822 (class 2606 OID 42050)
-- Name: habitaciones habitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT habitaciones_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 42000)
-- Name: hoteles hoteles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hoteles
    ADD CONSTRAINT hoteles_pkey PRIMARY KEY (id);


--
-- TOC entry 4838 (class 2606 OID 42192)
-- Name: limpieza_habitaciones limpieza_habitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.limpieza_habitaciones
    ADD CONSTRAINT limpieza_habitaciones_pkey PRIMARY KEY (id);


--
-- TOC entry 4816 (class 2606 OID 42027)
-- Name: metodo_pago metodo_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.metodo_pago
    ADD CONSTRAINT metodo_pago_pkey PRIMARY KEY (id);


--
-- TOC entry 4834 (class 2606 OID 42159)
-- Name: productos_habitaciones productos_habitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_habitaciones
    ADD CONSTRAINT productos_habitaciones_pkey PRIMARY KEY (id_producto, id_habitacion);


--
-- TOC entry 4820 (class 2606 OID 42039)
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- TOC entry 4826 (class 2606 OID 42083)
-- Name: productos_usuarios productos_usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_usuarios
    ADD CONSTRAINT productos_usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4824 (class 2606 OID 42067)
-- Name: reservas reservas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_pkey PRIMARY KEY (id);


--
-- TOC entry 4810 (class 2606 OID 41994)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 42009)
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 42179)
-- Name: contactos contactos_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contactos
    ADD CONSTRAINT contactos_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 4856 (class 2606 OID 42129)
-- Name: detalles_facturas detalles_facturas_id_factura_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_facturas
    ADD CONSTRAINT detalles_facturas_id_factura_fkey FOREIGN KEY (id_factura) REFERENCES public.facturas(id);


--
-- TOC entry 4857 (class 2606 OID 42134)
-- Name: detalles_facturas detalles_facturas_id_producto_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_facturas
    ADD CONSTRAINT detalles_facturas_id_producto_usuario_fkey FOREIGN KEY (id_producto_usuario) REFERENCES public.productos_usuarios(id);


--
-- TOC entry 4858 (class 2606 OID 42150)
-- Name: detalles_reserva detalles_reserva_id_habitacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_reserva
    ADD CONSTRAINT detalles_reserva_id_habitacion_fkey FOREIGN KEY (id_habitacion) REFERENCES public.habitaciones(id);


--
-- TOC entry 4859 (class 2606 OID 42145)
-- Name: detalles_reserva detalles_reserva_id_reserva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalles_reserva
    ADD CONSTRAINT detalles_reserva_id_reserva_fkey FOREIGN KEY (id_reserva) REFERENCES public.reservas(id);


--
-- TOC entry 4853 (class 2606 OID 42118)
-- Name: facturas facturas_id_hotel_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_id_hotel_fkey FOREIGN KEY (id_hotel) REFERENCES public.hoteles(id);


--
-- TOC entry 4854 (class 2606 OID 42113)
-- Name: facturas facturas_id_metodo_pago_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_id_metodo_pago_fkey FOREIGN KEY (id_metodo_pago) REFERENCES public.metodo_pago(id);


--
-- TOC entry 4855 (class 2606 OID 42108)
-- Name: facturas facturas_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas
    ADD CONSTRAINT facturas_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 4865 (class 2606 OID 42216)
-- Name: entidad_hija fkewpihqh8ik0nhvkldump7vrgn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entidad_hija
    ADD CONSTRAINT fkewpihqh8ik0nhvkldump7vrgn FOREIGN KEY (entidad_padre_id) REFERENCES public.entidad_padre(id);


--
-- TOC entry 4846 (class 2606 OID 42051)
-- Name: habitaciones habitaciones_id_hotel_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT habitaciones_id_hotel_fkey FOREIGN KEY (id_hotel) REFERENCES public.hoteles(id);


--
-- TOC entry 4847 (class 2606 OID 42056)
-- Name: habitaciones habitaciones_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT habitaciones_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 4863 (class 2606 OID 42198)
-- Name: limpieza_habitaciones limpieza_habitaciones_id_habitacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.limpieza_habitaciones
    ADD CONSTRAINT limpieza_habitaciones_id_habitacion_fkey FOREIGN KEY (id_habitacion) REFERENCES public.habitaciones(id);


--
-- TOC entry 4864 (class 2606 OID 42193)
-- Name: limpieza_habitaciones limpieza_habitaciones_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.limpieza_habitaciones
    ADD CONSTRAINT limpieza_habitaciones_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 4860 (class 2606 OID 42165)
-- Name: productos_habitaciones productos_habitaciones_id_habitacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_habitaciones
    ADD CONSTRAINT productos_habitaciones_id_habitacion_fkey FOREIGN KEY (id_habitacion) REFERENCES public.habitaciones(id);


--
-- TOC entry 4861 (class 2606 OID 42160)
-- Name: productos_habitaciones productos_habitaciones_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_habitaciones
    ADD CONSTRAINT productos_habitaciones_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 4845 (class 2606 OID 42040)
-- Name: productos productos_id_categoria_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_id_categoria_fkey FOREIGN KEY (id_categoria) REFERENCES public.categorias_productos(id);


--
-- TOC entry 4850 (class 2606 OID 42084)
-- Name: productos_usuarios productos_usuarios_id_producto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_usuarios
    ADD CONSTRAINT productos_usuarios_id_producto_fkey FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- TOC entry 4851 (class 2606 OID 42094)
-- Name: productos_usuarios productos_usuarios_id_reserva_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_usuarios
    ADD CONSTRAINT productos_usuarios_id_reserva_fkey FOREIGN KEY (id_reserva) REFERENCES public.reservas(id);


--
-- TOC entry 4852 (class 2606 OID 42089)
-- Name: productos_usuarios productos_usuarios_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.productos_usuarios
    ADD CONSTRAINT productos_usuarios_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 4848 (class 2606 OID 42073)
-- Name: reservas reservas_id_habitacion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_id_habitacion_fkey FOREIGN KEY (id_habitacion) REFERENCES public.habitaciones(id);


--
-- TOC entry 4849 (class 2606 OID 42068)
-- Name: reservas reservas_id_usuario_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_id_usuario_fkey FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- TOC entry 4843 (class 2606 OID 42015)
-- Name: usuarios usuarios_id_hotel_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_hotel_fkey FOREIGN KEY (id_hotel) REFERENCES public.hoteles(id);


--
-- TOC entry 4844 (class 2606 OID 42010)
-- Name: usuarios usuarios_id_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_id_rol_fkey FOREIGN KEY (id_rol) REFERENCES public.roles(id);


-- Completed on 2025-06-17 19:18:23

--
-- PostgreSQL database dump complete
--

